apiVersion: v1
kind: Service
metadata:
 labels:
   name: {{ .Values.app.prefix }}-app-db
 name: {{ .Values.app.prefix }}-app-db
 namespace: {{ .Values.app.namespace }}
spec:
 type: NodePort
 ports:
 - name: mongo-db
   port: 27017
   targetPort: 27017
 selector:
   name: {{ .Values.app.prefix }}-app-db