apiVersion: v1
kind: Service
metadata:
  labels:
    name: {{ .Values.app.prefix }}-camunda-pod
  name: {{ .Values.app.prefix }}-camunda-pod
  namespace: {{ .Values.app.namespace }}
spec:
  type: NodePort
  ports:
  - name: {{ .Values.service.camundapod.name }}
    port: 8080
    targetPort: 8080
  selector:
    name: {{ .Values.app.prefix }}-camunda-pod