---
openapi: 3.0.0
info:
   version: 1.3.0
   title: dakishan open api specification
   description: systementry API
   termsOfService: http://api_url/terms/
   contact:
      name: ContactName
      email: hello@wolox.co
      url: https://www.wolox.com.ar/
   license:
      name: Apache 2.0
      url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
   - url: http://localhost:8010
     description: systementry
tags:
- name: User
  description: User details
paths:
   "/systemEntryFeature/userdata/{id}":
      get:
         tags:
         -  User
         description: GpSEF
         parameters:
         -  in: "path"
            description: GpSEF
            name: id
            required: true
            schema:
               type: "string"
         responses:
            200:
               description: Success
            400:
               description: Bad Request
            404:
               description: Not Found
            500:
               description: Internal Server Error
components:
   schemas:
      User:
         type: object
         properties:
            firstname:
               type: "string"
               description: user first name
            lastname:
               type: "string"
               description: user last name
            username:
               type: "string"
               description: username
            email:
               type: "string"
               description: user Email
            password:
               type: "string"
               description: user password
            phonenumber:
               type: "string"
               description: user phone number
            avatar:
               type: "string"
               description: user profile avatar
            Idtoken:
               type: "string"
               description: Jwt token of user details
            loggedinDate:
               type: "date"
               description: user Logged in date
            loggedoutDate:
               type: "date"
               description: user Logged out date
            role:
               type: "{ type: mongoose.schema.types.string, ref: 'roles' }"
               description: Role of the User
            org:
               type: "string"
               description: Organization name
            org_country:
               type: "string"
               description: Country of the organization
            org_sub1:
               type: "string"
               description: Sub organization one
            org_sub2:
               type: "string"
               description: Sub organization two
            org_sub3:
               type: "string"
               description: Sub organization three