kind: Service
apiVersion: v1
metadata:
  name: elasticsearch
  namespace: {{ .Values.logging.namespace }}
  labels:
    app: elasticsearch
spec:
  type: NodePort
  selector:
    app: elasticsearch
  ports:
    - port: 9200
      name: rest
      nodePort: 30194
    - port: 9300
      name: inter-node
      nodePort: 30195