apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data
  namespace: {{ .Values.logging.namespace }}
  labels:
    app: elasticsearch
spec:
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 10Gi