apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.app.prefix }}-app-mongo-data
  namespace: {{ .Values.app.namespace }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistentVolumeClaim.mongo.storage }}